Wrong HTTP port publish argument shown in docker docs
NLnetLabs/routinator pull request #809
Opened 2022-10-17 15:27 UTC by ximon18

This PR builds on the Docker documentation changes made in PR #796 and aims to resolve issue #808.

2022-10-19 08:59 UTC, AlexanderBand requested changes

2022-10-19 08:59 UTC, AlexanderBand commented on doc/manual/source/installation.rst
> +       server on port 3323 and HTTP server on port 9556) can be done like so:
```suggestion
       server on port 3323 and HTTP server on port 8323) can be done like so:
```
Should this be 8323?

2022-10-19 10:51 UTC, ximon18 commented on doc/manual/source/installation.rst
> +       server on port 3323 and HTTP server on port 9556) can be done like so:
Errm, yes, good catch.

2022-10-19 11:21 UTC, AlexanderBand approved these changes

2022-11-02 11:18 UTC, partim approved these changes

2022-11-02 11:29 UTC, ximon18 commented
@partim, @AlexanderBand and @DRiKE: This branch became quite outdated and conflicted compared to master so I made the changes again on a clean copy of `main` and updated this PR to reflect ONLY those changes. I separated out some unrelated changes that were made for #805 into new PR #813.

2022-11-02 12:35 UTC, merged